Django-sky/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import BlogConfig
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('list/', BlogListView.as_view(), name='blogpost_list'),
    path('сreate/', BlogCreateView.as_view(), name='blogpost_create'),
    path('detail/<int:pk>/',  cache_page(60)(BlogDetailView.as_view()), name='blogpost_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blogpost_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blogpost_delete'),
]

Django-sky/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace=',blog')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('mailings/', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-sky/mailings/urls.py
from mailings.apps import MailingsConfig
from django.urls import path
from .views import (
    ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView,
    MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView
)


app_name = MailingsConfig.name

urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/edit/', ClientUpdateView.as_view(), name='client_edit'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/edit/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
]

Django-sky/mailings/models.py
from django.db import models
from django.utils import timezone
from django.utils.timezone import now

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name="контактный email")
    full_name = models.CharField(max_length=250, verbose_name="ФИО")
    comment = models.TextField(blank=True, null=True, verbose_name="Комментарий")

    def __str__(self):
        return f"{self.full_name} ({self.email})"

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Mailing(models.Model):
    minute = 'Раз в минуту'
    hour = 'Раз в час'
    daily = 'Раз в день'
    weekly = 'Раз в неделю'
    monthly = 'Раз в месяц'

    created = 'Создана'
    started = 'Запущена'
    finished = 'Завершена'

    PERIODICITY_CHOICES = [
        ('minute', 'Раз в минуту'),
        ('hour', 'Раз в час'),
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    ]

    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('finished', 'Завершена'),
    ]

    start_datetime = models.DateTimeField(default=now, verbose_name="Дата создания")
    stop_datetime = models.DateTimeField(default=now, verbose_name="Дата окончания рассылки")
    periodicity = models.CharField(max_length=10, choices=PERIODICITY_CHOICES, verbose_name="Периодичность")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created', verbose_name="Статус рассылки")
    subject = models.CharField(max_length=255, verbose_name="Тема письма")
    body = models.TextField(verbose_name="Текст письма")
    client = models.ManyToManyField(Client, verbose_name='клиент')

    def __str__(self):
        return f"Рассылка {self.id} - {self.get_status_display()}"

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class Attempt(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    attempt_date = models.DateTimeField(default=timezone.now, verbose_name="Дата попытки")
    status = models.BooleanField(default=False, verbose_name="Статус попытки")
    server_response = models.TextField(blank=True, null=True, verbose_name="Ответ сервера")

    def __str__(self):
        return f"Попытка {self.mailing.id} to {self.client.email} at {self.attempt_date}"

    class Meta:
        verbose_name = 'Попытка'
        verbose_name_plural = 'Попытки'

Django-sky/mailings/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget

from .models import Client, Mailing


class DateInput(forms.DateInput):
    input_type = 'date'


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['email', 'full_name', 'comment']


class MailingForm(forms.ModelForm):

    start_datetime = forms.DateField(widget=DateInput)
    stop_datetime = forms.DateField(widget=DateInput)

    class Meta:
        model = Mailing
        fields = ['start_datetime', 'stop_datetime', 'periodicity', 'status', 'subject', 'body', 'client']

Django-sky/mailings/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Client, Mailing
from .forms import ClientForm, MailingForm
from django import forms


# Client views
class ClientListView(ListView):
    model = Client
    template_name = 'mailings/client_list.html'
    success_url = reverse_lazy('mailings:client_list')


class ClientDetailView(DetailView):
    model = Client
    template_name = 'mailings/client_detail.html'
    success_url = reverse_lazy('mailings:client_list')


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
#    fields = ('email', 'full_name', 'comment')
    template_name = 'mailings/client_form.html'
    success_url = reverse_lazy('mailings:client_list')


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
#    fields = ('email', 'full_name', 'comment')
    template_name = 'mailings/client_form.html'
    success_url = reverse_lazy('mailings:client_list')


class ClientDeleteView(DeleteView):
    model = Client
    template_name = 'mailings/client_confirm_delete.html'
    success_url = reverse_lazy('mailings:client_list')


# Mailing views
class MailingListView(ListView):
    model = Mailing
    template_name = 'mailings/mailing_list.html'
    context_object_name = 'mailings'
    success_url = reverse_lazy('mailings:mailing_list')


class MailingDetailView(DetailView):
    model = Mailing
    template_name = 'mailings/mailing_detail.html'
    success_url = reverse_lazy('mailings:mailing_detail')


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
#    fields = ('start_datetime', 'stop_datetime', 'periodicity', 'status', 'subject', 'body', 'client')
    template_name = 'mailings/mailing_form.html'
    success_url = reverse_lazy('mailings:mailing_list')


class MailingUpdateView(UpdateView):
    model = Mailing
#    form_class = MailingForm
    fields = ('start_datetime', 'stop_datetime', 'periodicity', 'status', 'subject', 'body', 'client')
    template_name = 'mailings/mailing_form.html'
    success_url = reverse_lazy('mailings:mailing_list')


class MailingDeleteView(DeleteView):
    model = Mailing
    template_name = 'mailings/mailing_confirm_delete.html'
    success_url = reverse_lazy('mailings:mailing_list')

Django-sky/mailings/templates/mailings/client_confirm_delete.html
{% extends 'main/index.html' %}

{% block content %}
<h2>Delete Client</h2>
<p>Are you sure you want to delete "{{ client.full_name }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
</form>
<a href="{% url 'mailings:client_list' %}">Cancel</a>
{% endblock %}

Django-sky/mailings/templates/mailings/client_detail.html
{% extends 'main/index.html' %}

{% block content %}
<h2>{{ client.full_name }}</h2>
<p>Email: {{ client.email }}</p>
<p>Comment: {{ client.comment }}</p>
<a href="{% url 'mailings:client_list' %}">Back to list</a>
{% endblock %}

Django-sky/mailings/templates/mailings/client_form.html
{% extends 'main/index.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="col-8 card-body">
                        <form method='post'>
                            {% csrf_token %}
                            {{ form.as_p }}
                                {% if object %}
                                    <button type="submit" class="btn btn-xs btn-block btn-outline-primary">Сохранить</button>
                                    <a href="{% url 'mailings:client_list' %}" class="btn btn-xs btn-block btn-outline-primary">Назад</a>
                                {% else %}
                                    <button type="submit" class="btn btn-xs btn-block btn-outline-primary">Создать</button>
                                    <a href="{% url 'mailings:client_list' %}" class="btn btn-xs btn-block btn-outline-primary">Назад</a>
                                {% endif %}
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Django-sky/mailings/templates/mailings/client_list.html
{% extends 'main/index.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-1 pb-md-2 mx-auto text-center">
    <h6 class="display-6 mb-3 mt-0">Страница клиентов</h6>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ object.full_name|title }}</p>
                        <p class="card-text">email: {{ object.email }}</p>
                        <p class="card-text">Комментарии: {{ object.comment }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn">
                                <a class="p-2 mb-4 mt-2 btn btn-outline-primary" href="{% url 'mailings:client_detail' object.pk %}"
                                   role="button">Посмотреть</a>
                                <a class="p-2 mb-4 mt-2 btn btn-outline-primary" href="{% url 'mailings:client_edit' object.pk %}"
                                   role="button">Редактировать</a>
                                <a class="p-2 mb-4 mt-2 btn btn-outline-primary" href="{% url 'mailings:client_delete' object.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
<a class="p-2 mb-4 mt-2 btn btn-outline-primary" href="{% url 'mailings:client_create' %}">Создать клиента</a>
    </div>
</div>
{% endblock %}

Django-sky/mailings/templates/mailings/mailing_confirm_delete.html
{% extends 'main/index.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-4 text-center">
                <div class="card">
                    <div class="card-body">
                        <form method='post'>
                            {% csrf_token %}
                            <p>Хотите удалить рассылку "{{ object.title|title }}"?</p>
                            <button type="submit" class="p-2 mb-4 mt-2 btn btn-outline-primary">Подтвердить</button>
                            <a class="p-2 mb-4 mt-2 btn btn-outline-primary" href="{% url 'mailings:mailing_list' %}" role="button">Отменить</a>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

<!--

<h2>Delete Mailing</h2>
<p>Are you sure you want to delete mailings {{ mailings.id }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
</form>
<a href="{% url 'mailings:mailing_list' %}">Cancel</a>
 -->

Django-sky/mailings/templates/mailings/mailing_detail.html
{% extends 'main/index.html' %}

{% block content %}
<h2>Mailing {{ object.title }}</h2>
<p>Status: {{ object.get_status_display }}</p>
<p class="card-text">Комментарий: {{ object.comment }}</p>
<p>Дата создания рассылки: {{ object.start_datetime }}</p>
<p>Дата окончания рассылки: {{ object.stop_datetime }}</p>
<p>Периодичность: {{ object.get_periodicity_display }}</p>
<a href="{% url 'mailings:mailing_list' %}">Back to list</a>
{% endblock %}

Django-sky/mailings/templates/mailings/mailing_form.html
{% extends 'main/index.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method='post'>
                            {% csrf_token %}
                            {{ form.as_p }}
                                {% if object %}
                                    <button type="submit" class="btn btn-xs btn-block btn-outline-primary">Сохранить</button>
                                    <a href="{% url 'mailings:mailing_list' %}" class="btn btn-xs btn-block btn-outline-primary">Назад</a>
                                {% else %}
                                    <button type="submit" class="btn btn-xs btn-block btn-outline-primary">Создать</button>
                                    <a href="{% url 'mailings:mailing_list' %}" class="btn btn-xs btn-block btn-outline-primary">Назад</a>
                                {% endif %}
                            </button>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Django-sky/mailings/templates/mailings/mailing_list.html
{% extends 'main/index.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h5 class="display-6">Страница рассылок</h5>
</div>


<div class="container col-10">
    <div class="card">
        <div class="card-header text-center">
            <h5>Рассылки</h5>
        </div>
        <div class="card-body">
            <div class="col-12 text-center">
                <table class="table">
                    <tr>
                        <th><h6>Дата начала рассылки</h6></th>
                        <th><h6>Дата окончания рассылки</h6></th>
                        <th><h6>Периодичность рассылки</h6></th>
                        <th><h6>Статус рассылки</h6></th>
                        <th><h6>Тема</h6></th>
                        <th><h6>Посмотреть рассылку</h6></th>
                        <th><h6>Редактировать рассылку</h6></th>
                        <th><h6>Удалить рассылку</h6></th>
                    </tr>
                    {% for object in object_list %}
                    <tr>
                        <td><h6>{{ object.start_datetime}}</h6></td>
                        <td><h6>{{ object.stop_datetime}}</h6></td>
                        <td><h6>{{ object.get_periodicity_display }}</h6></td>
                        <td><h6>{{ object.get_status_display }}</h6></td>
                        <td><h6>{{ object.body }}</h6></td>
                        <td><h6>
                            <a class="p-2 mb-4 mt-2 btn btn-outline-primary"
                               href="{% url 'mailings:mailing_detail' object.pk %}">Просмотр</a>
                        </h6></td>
                        <td><h6>
                            <a class="p-2 mb-4 mt-2 btn btn-outline-primary"
                               href="{% url 'mailings:mailing_edit' object.pk %}">Редактирование</a>
                        </h6></td>
                        <td><h6>
                            <a class="p-2 mb-4 mt-2 btn btn-outline-primary"
                               href="{% url 'mailings:mailing_delete' object.pk %}">Удаление</a>
                        </h6></td>
                    {% endfor %}
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="row text-right mt-4">
        <div class="col-12">
            <a class="p-2 mb-4 mt-2 btn btn-outline-primary" href="{% url 'mailings:mailing_create' %}">Создать рассылку</a>
        </div>
    </div>
</div>
{% endblock %}