Django-sky/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import BlogConfig
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('list/', BlogListView.as_view(), name='blogpost_list'),
    path('сreate/', BlogCreateView.as_view(), name='blogpost_create'),
    path('detail/<int:pk>/',  cache_page(60)(BlogDetailView.as_view()), name='blogpost_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blogpost_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blogpost_delete'),
]

Django-sky/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace=',blog')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('mailings/', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-sky/mailings/urls.py
from mailings.apps import MailingsConfig
from django.urls import path
from .views import (
    ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView,
    MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, MailingDeleteView
)


app_name = MailingsConfig.name

urlpatterns = [
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/edit/', ClientUpdateView.as_view(), name='client_edit'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/edit/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
]

Django-sky/main/urls.py
from django.urls import path

from shop.views import contacts
from .apps import MainConfig
from .views import base, not_found

app_name = MainConfig.name

urlpatterns = [
    path('', base, name='main'),
    path('contacts/', contacts, name='contacts'),
    path('not_found/', not_found, name='not_found'),
]

Django-sky/shop/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import ShopConfig
from .views import ProductListView, contacts, ProductCreateView, ProductDetailView, ProductUpdateView, ProductDeleteView

app_name = ShopConfig.name


urlpatterns = [
    path('product/', ProductListView.as_view(), name='product_list'),
    path('contacts/', contacts, name='contacts'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/detail/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

Django-sky/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .apps import UsersConfig
from .views import RegisterView, verify_email, PasswordResetView, ProfileUpdateView, UserLogoutView, CustomLoginView


app_name = UsersConfig.name

urlpatterns = [
    #path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
#    path('login2/', UserLoginForm(), name='login2'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify-email/<uuid:token>/', verify_email, name='verify_email'),
    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_update'),


]

Django-sky/main/models.py
from django.db import models

# Create your models here.

Django-sky/main/views.py
from django.shortcuts import render


def base(request):
    return render(request, 'main/index.html')


def contacts(request):
    return render(request, 'main/contacts.html')


def not_found(request):
    return render(request, 'main/not_found.html')

Django-sky/main/templates/main/contacts.html
{% extends 'main/index.html' %}
{% load static %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td> Российская Федерация</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>7707543124</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>г. Москва, ул. Скаковая, д. 17 стр. 2.</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Контактный телефон" required></textarea>
                            </div>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Django-sky/main/templates/main/index.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django-sky {{ title }} </title>
    <link href="{% static 'ico/candygold.ico' %}" rel="icon" type="image/x-icon">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body {
            padding-top: 60px; /* Adjust based on the height of your navbar */
        }
    </style>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-1 px-md-2 mb-1 bg-white border-bottom box-shadow fixed-top">
    <h4 class="my-0 mr-md-auto font-weight-normal">Django-sky</h4>
    <nav class="ms-2">
        <a class="p-2 btn btn-outline-primary" href="{% url 'main:main' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="/admin">Админка</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'shop:product_list' %}">Магазин</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blogpost_list' %}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown"
           aria-expanded="false">
            Рассылка</a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% url 'mailings:client_list' %}">Страница клиентов</a>
            <a class="dropdown-item" href="{% url 'mailings:mailing_list' %}">Страница рассылок</a>
        </ul>
    </nav>
    <nav class="px-md-2 ms-auto navbar-nav navbar-right">
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="#" role="button" id="dropdownMenuLink"
               data-bs-toggle="dropdown"
               aria-expanded="false">{{ user.email }}</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="#" role="button" id="dropdownMenuLink"
               data-bs-toggle="dropdown"
               aria-expanded="false">Login</a>
        {% endif %}

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'users:logout' %}">Выход</a>
                <a class="dropdown-item" href="{% url 'users:profile_update' %}">Профиль</a>
            {% else %}
                <a class="dropdown-item" href="{% url 'users:login' %}">Вход</a>
                <a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a>
            {% endif %}
        </ul>
    </nav>
</div>

<div class="pricing-header col-6 px-1 py-1 pt-md-2 pb-md-2 mx-auto text-center">
    {% block center %}
    {% endblock %}

    {% if request.path == '/' %}

        <!-- Image -->
        <img src="{% static 'img/illustrations/illustration-2.png' %}"
             class="img-fluid mw-md-150 mw-lg-130 mb-6 mb-md-0 aos-init aos-animate"
             alt="..." data-aos="fade-up" data-aos-delay="100">

        <!--    <h5 class="display-6 text-center">MARKET_SKY</h5> -->
        <!--    <p class="lead">MARKET_SKY - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
                продать</p> -->
    {% endif %}
</div>

<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Django-sky
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'shop:product_list' %}">Магазин</a></li>
                    <li><a class="text-muted" href="{% url 'blog:blogpost_list' %}">Блог</a></li>
                    <li><a class="text-muted" href="{% url 'mailings:client_list' %}">Рассылка</a></li>

                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'main:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
</body>
</html>

Django-sky/main/templates/main/not_found.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Bootstrap 5 404 Error Page</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>

<body>
<div class="d-flex align-items-center justify-content-center vh-100">
    <div class="text-center">
          
        {% if messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

        <h1 class="display-1 fw-bold">404</h1>
        <p class="fs-3"><span class="text-danger">Opps!</span> Page not found.</p>
        <p class="lead">
            The page you’re looking for doesn’t exist.
        </p>
        <a href="{% url 'main:main' %}" class="btn btn-primary">Go Home</a>
    </div>
</div>
</body>

</html>