Django-sky/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import BlogConfig
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('list/', BlogListView.as_view(), name='blogpost_list'),
    path('сreate/', BlogCreateView.as_view(), name='blogpost_create'),
    path('detail/<int:pk>/',  cache_page(60)(BlogDetailView.as_view()), name='blogpost_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blogpost_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blogpost_delete'),
]

Django-sky/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace=',blog')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('mailings/', include('mailings.urls', namespace='mailings')),
    path('users/', include('users.urls', namespace='users')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-sky/shop/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import ShopConfig
from .views import ProductListView, contacts, ProductCreateView, ProductDetailView, ProductUpdateView, ProductDeleteView

app_name = ShopConfig.name


urlpatterns = [
    path('product/', ProductListView.as_view(), name='product_list'),
    path('contacts/', contacts, name='contacts'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/detail/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

Django-sky/shop/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


# class PublishedProductManager(models.Manager):
#     def get_queryset(self):
#         return super().get_queryset().filter(is_published='published')
#
#
# class UnpublishedProductManager(models.Manager):
#     def get_queryset(self):
#         return super().get_queryset().filter(is_published='draft')


class Product(models.Model):

    STATUS_CHOICES = [
        ('draft', 'Черновик'),
        ('published', 'Опубликовано'),
        ('archived', 'В архиве'),
    ]

    name = models.CharField(max_length=255, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    weight = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Вес товара', null=True, blank=True)
    image = models.ImageField(upload_to='shop/', verbose_name='Изображение (превью)', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Автор')
    is_published = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft', verbose_name='Статуса публикации')
#    manufactured_at = models.DateField(verbose_name='Дата производства')

    # published = PublishedProductManager()
    # unpublished = UnpublishedProductManager()

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ['-created_at']
        permissions = [
            ('can_edit_product_publication', 'Can edit product publication'),
            ('can_edit_product_description', 'Can edit product description'),
            ('can_edit_product_category', 'Can edit product category'),
        ]

    def __str__(self):
        return self.name


class Version(models.Model):
    product = models.ForeignKey(Product, related_name='versions', on_delete=models.CASCADE, verbose_name="Продукт")
    version_number = models.CharField(max_length=50, verbose_name="Номер версии")
    version_name = models.CharField(max_length=255, verbose_name="Название версии")
    is_current = models.BooleanField(default=False, verbose_name="Текущая версия")

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        constraints = [
            # models.UniqueConstraint(fields=['product', 'version_name'], name='unique_version_name_per_product'),
            models.UniqueConstraint(fields=['product', 'version_name', 'version_number'],
                                    name='unique_version_per_product')
        ]

    def __str__(self):
        return f'{self.version_name} ({self.version_number})'

Django-sky/shop/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BaseInlineFormSet, inlineformset_factory, ModelForm
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Product, Version


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['owner']
        fields = "__all__"

    def clean_name(self):
        name = self.cleaned_data.get('name')
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in forbidden_words:
            if word in name.lower():
                raise forms.ValidationError(f'Название содержит запрещенное слово: {word}')
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in forbidden_words:
            if word in description.lower():
                raise forms.ValidationError(f'Описание содержит запрещенное слово: {word}')
        return description


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ['version_name', 'version_number', 'is_current']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.fields['is_current'].widget.attrs.update({'class': 'form-check-input'})

    def clean(self):
        cleaned_data = super().clean()
        version_name = cleaned_data.get('version_name')
        version_number = cleaned_data.get('version_number')
        product = self.instance.product
        if Version.objects.filter(product=product, version_number=version_number, version_name=version_name).exclude(
                pk=self.instance.pk).exists():
            raise ValidationError(
                f'Версия с названием "{version_name}" и номером "{version_number}" уже существует для данного продукта.')
        return cleaned_data


class BaseVersionFormSet(BaseInlineFormSet):
    def clean(self):
        super().clean()
        current_count = 0
        for form in self.forms:
            if form.cleaned_data.get('is_current'):
                current_count += 1
        if current_count > 1:
            raise ValidationError('Вы можете выбрать только одну текущую версию продукта.')


class ProductModeratorForm(LoginRequiredMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')

Django-sky/shop/views.py
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory, BaseInlineFormSet, ModelForm
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.decorators.cache import never_cache, cache_page
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from shop.forms import ProductForm, VersionForm, BaseVersionFormSet, ProductModeratorForm
from shop.models import Product, Version


class ProductListView(ListView):
    model = Product
    template_name = 'shop/product_list.html'
    context_object_name = 'products'
    paginate_by = 3

    def get_queryset(self):
        if self.request.user.groups.filter(name='Moderator_Product').exists() or self.request.user.groups.filter(
                name='Admin').exists() or self.request.user.groups.filter(name='User_Product').exists():
            return Product.objects.all()
        return Product.objects.filter(is_published='published')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products_with_versions = []

        for product in context['products']:
            current_version = product.versions.filter(is_current=True).first()
            products_with_versions.append((product, current_version))

        context['products_with_versions'] = products_with_versions
        return context


class ProductDetailView(DetailView):  # Переопределяем DetailView
    model = Product
    template_name = 'shop/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        current_version = product.versions.filter(is_current=True).first()
        context['current_version'] = current_version
        return context


# def product_create(request):
#     if request.method == 'POST':
#         form = ProductForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('product_list')
#     else:
#         form = ProductForm()
#     return render(request, 'catalog/product_form.html', {'form': form})
#


class ProductCreateView(CreateView):  # Переопределяем CreateView для создания продукта
    model = Product
    form_class = ProductForm
    template_name = 'shop/product_create.html'
    #    fields = ['name', 'description', 'price', 'weight', 'category', 'image']
    success_url = reverse_lazy('shop:product_list')

    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        """Отключение кеша"""
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.owner = self.request.user  # Устанавливаем текущего пользователя как владельца
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'shop/product_update.html'

    def dispatch(self, request, *args, **kwargs):
        product = self.get_object()
        # print(product.owner)
        # print(self.request.user)
        user = self.request.user

        has_permission = (
                user.groups.filter(name='Admin').exists() or
                user.groups.filter(name='Moderator_Product').exists() or
                product.owner == user
        )

        if not has_permission:
            # raise PermissionDenied("Вы не можете изменять этот продукт.")
            messages.success(self.request, 'Вы не может изменять не свои продукты,'
                                           'так как вы не являетесь его владельцем.')
            return redirect('main:not_found')
        return super().dispatch(request, *args, **kwargs)

        # if product.owner != self.request.user:
        #     # raise PermissionDenied("Вы не может изменять не свои продукты.")
        #     messages.success(self.request, 'Вы не может изменять не свои продукты,'
        #                                    'так как вы не являетесь его владельцем.')
        #     if self.request.user.groups.filter(name='Admin').exists():
        #         return super().dispatch(request, *args, **kwargs)
        #
        #     return redirect('main:not_found')
        #
        # return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Инициализируем формсет для версий продукта.
        #  Выбирает без сообщения последнюю отмеченную версию.
        # VersionFormSet = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        #  Не даст выбрать две версии продукта выводит сообщение.
        VersionFormSet = inlineformset_factory(Product, Version, form=VersionForm, extra=1, formset=BaseVersionFormSet)

        if self.request.method in ['POST', 'PUT']:
            # Если есть POST-запрос, передаем данные формы и формсета
            context['formset'] = VersionFormSet(self.request.POST, instance=self.object)
        else:
            # Если GET-запрос, создаем формсет для текущего экземпляра продукта
            context['formset'] = VersionFormSet(instance=self.object)

        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']

        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            instances = formset.save(commit=False)
            for instance in instances:
                if instance.is_current:
                    Version.objects.filter(product=self.object, is_current=True).exclude(pk=instance.pk).update(
                        is_current=False)
                instance.product = self.object
                instance.save()
            formset.save_m2m()

            # Удаление форм, помеченных для удаления
            for form in formset.deleted_forms:
                if form.instance.pk:
                    form.instance.delete()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    # def get_object(self, queryset=None):
    #     return self.request.user

    def get_success_url(self):
        # return reverse_lazy('shop:product_update', kwargs={'pk': self.object.pk})
        return reverse_lazy('shop:product_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.groups.filter(name='Admin').exists():
            return ProductForm
        elif (user.has_perm('shop.can_edit_product_publication') and
              user.has_perm('shop.can_edit_product_description') and
              user.has_perm('shop.can_edit_product_category')):
            return ProductModeratorForm
        else:
            return PermissionDenied
            # return redirect('main:not_found')


class ProductDeleteView(DeleteView):
    model = Product  # Переопределяем DeleteView для удаления продукта
    fields = ['name', 'description', 'price', 'weight', 'category', 'image']
    template_name = 'shop/product_delete.html'
    success_url = reverse_lazy('shop:product_list')

    def dispatch(self, request, *args, **kwargs):
        product = self.get_object()

        if product.owner != self.request.user:
            # raise PermissionDenied("Вы не может удалять не свои продукты")
            messages.success(self.request, 'Вы не может удалять не свои продукты, '
                                           'так как вы не являетесь его владельцем.')
            return redirect('main:not_found')

        return super().dispatch(request, *args, **kwargs)


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Имя: {name}, Телефон: {phone}, Сообщение: {message}')

    return render(request, 'main/contacts.html', {'contacts': contacts})

Django-sky/shop/templates/shop/product_create.html
<!-- templates/catalog/product_create.html -->
{% extends 'main/index.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center calc">
        <h2>Создать продукт</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-xs btn-block btn-outline-primary">Сохранить</button>
                <a href="{% url 'shop:product_list' %}" class="btn btn-xs btn-block btn-outline-primary">Назад</a>
            </form>
    </div>
</div>
{% endblock %}

Django-sky/shop/templates/shop/product_delete.html
<!-- templates/catalog/product_delete.html-->
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center calc">
            <h2>Вы уверены, что хотите удалить продукт ? </h2>
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_p }}
                <div class="col-md-5">
                    <img src="{{ product.image | media_files }}" class="img-fluid" alt="{{ product.name }}">
                </div>
                <div class="col-md-6">
                    <h3>{{ product.name }}</h3>
                    <p>Категория: {{ product.category.name }}</p>
                    <p>Цена: {{ product.price }} ₽</p>
                    <p>Описание: {{ product.description }}</p>
                    <button type="submit" class="btn btn-danger">Да,удалить</button>
                    <a class="btn btn-xs btn-block btn-outline-primary" href="{% url 'shop:product_list'  %}">Отменить</a>
                    </div>
            </form>
        </div>
    </div>
{% endblock %}

Django-sky/shop/templates/shop/product_detail.html
<!-- templates/catalog/product_detail.html -->
{% extends 'main/index.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ product.image | media_files }}" class="img-fluid" alt="{{ product.name }}">
        </div>
        <div class="col-md-6">
            <p><h3>Продукт: {{ product.name }}</h3></p>
            <p>Версия: {{ current_version.version_name }} ({{current_version.version_number }})</p>
            <p>Категория: {{ product.category.name }}</p>
            <p>Цена: {{ product.price }} ₽</p>
            <p>Вес: {{ product.weight }}</p>
            <p>Описание: {{ product.description }}</p>
            <p>Автор: {{ product.owner }}</p>
            <button type="button" class="btn btn-xs btn-block btn-outline-primary">Купить</button>
            <a href="{% url 'shop:product_list' %}" class="btn btn-xs btn-block btn-outline-primary">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

Django-sky/shop/templates/shop/product_form.html
<!-- templates/catalog/product_create.html -->
{% extends 'main/index.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center calc">
        {% if object.id %}
            <h2>Изменить продукт</h2>
        {% else %}
            <h2>Создать продукт</h2>
        {% endif  %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </form>
    </div>
</div>
{% endblock %}

Django-sky/shop/templates/shop/product_list.html
{% extends 'main/index.html' %}
{% load crispy_forms_tags %}
{% block center %}
    <div class="pricing-header px-3 py-3 pt-md-1 pb-md-2 mx-auto text-center">
        <h6 class="display-6 mb-3 mt-0">Страница магазина</h6>
    </div>
{% endblock %}
{% load my_tags %}
{% block content %}
{% if object_list %}
    <div class="row text-center">
        {% for product, current_version in products_with_versions %}
            <div class="p-1 col-4">
                <div class="card mx-auto">
                    <div class="card-header div-fixed-size">
                        <img src="{{ product.image | media_files }}" class="img-fluid" style="height: 300px;">
                    </div>
                    <div class="card-body">
                        <ul class="mt-2 mb-2 text-start">
                            <!--                       <li>Продукт: {{ product.name | slice:":30" }}</li>-->
                            <li>Продукт: {{ product.name | truncate_chars:30 }}</li>
                            {% if current_version %}
                            <li>Версия: {{ current_version.version_name }} ({{ current_version.version_number }})</li>
                            {% else  %}
                               <li>Версия: Версия отсутствует</li>
                            {% endif %}
                            <li>Категория: {{ product.category.name | truncate_chars:30 }}</li>
                            <li>Вес: {{ product.weight }}</li>
                            <li>Цена: {{ product.price }} ₽</li>
                        </ul>
                        <button class="btn btn-xs btn-block btn-outline-primary">Купить</button>
                        <a class="btn btn-xs btn-block btn-outline-primary"
                           href="{% url 'shop:product_detail' product.pk %}">Подробно</a>
                        {% if user.is_authenticated %}
                        <a class="btn btn-xs btn-block btn-outline-primary"
                           href="{% url 'shop:product_update' product.pk %}">Изменить</a>
                           <a class="btn btn-xs btn-block btn-outline-primary"
                           href="{% url 'shop:product_delete' product.pk %}">Удалить</a>
                       {% else %}
                           <a class="btn btn-secondary" href="">Изменить</a>
                           <a class="btn btn-secondary" href="">Удалить</a> 
                       {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
    <h4 class="text-center my-0 mr-md-auto font-weight-normal">Нет ни единого продукта</h4>
    {% endif %}
    {% if user.is_authenticated %}
        <a class="p-2 mb-4 mt-2 btn btn-outline-primary" href="{% url 'shop:product_create' %}">Создать продукт</a>
    {% else %}
        <a class="p-2 mb-4 mt-2 btn btn btn-secondary" href="">Создать продукт</a>   
    {% endif %}


    <!-- Пагинация -->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">Первый</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущий</a>
                </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active">
                        <span class="page-link">{{ num }}</span>
                    </li>
                {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующий</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последний</a>
                </li>
            {% endif %}
        </ul>
    </nav>

{% endblock %}

Django-sky/shop/templates/shop/product_update.html
{% extends 'main/index.html' %}
{% load crispy_forms_filters %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Изменить продукт</h2>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary mt-3">Сохранить</button>
            <a href="{% url 'shop:product_list' %}" class="btn btn-secondary mt-3">Назад</a>
        </div>
        <div class="col-md-6" style="max-height: 800px; overflow-y: auto;">
            <h3>Версии продукта</h3>
            {{ formset.management_form }}
            {{ formset.non_form_errors }}
            <div class="list-group">
                {% for form in formset %}
                <div class="list-group-item">
                    {{ form.as_p }}
                </div>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary mt-3">Сохранить</button>
        </div>
    </div>
</form>
{% endblock %}